build: bump Angular dependencies and drop benchpress
angular/components pull request #22390
Opened 2021-04-02 07:27 UTC by crisbeto

* Updates the `@angular` dependencies to the latest versions.
* Removes the depenency on `@angular/benchpress` since we weren't using it and it was causing some issues in the snapshot builds.

2021-04-02 13:26 UTC, devversion approved these changes
LGTM

2021-04-02 15:23 UTC, josephperrott requested changes
An issue with validating commits was found for when multiple level scopes as used and will be fixed with: https://github.com/angular/angular/pull/41430#pullrequestreview-627042875

The dev-infra-private-builds version needs to include this change.

2021-04-02 17:50 UTC, josephperrott approved these changes
LGTM

2021-04-02 17:50 UTC, josephperrott commented on package.json
> +    "@angular/dev-infra-private": "https://github.com/angular/dev-infra-private-builds.git#ebf0a487a4de71746b5b025e4e7878ca5714ba46",
```suggestion
    "@angular/dev-infra-private": "https://github.com/angular/dev-infra-private-builds.git#3953ba9eea35a2660b6068523bafb92634042be9",
```

2021-04-06 03:07 UTC, annieyw commented
@crisbeto  needs rebase

2021-04-06 06:39 UTC, crisbeto commented
Rebased.

2021-04-07 05:06 UTC, merged