fix(cdk/overlay): fix overlay margin in isBoundedByLeftViewportEdge
angular/components pull request #28233
Opened 2023-12-05 00:54 UTC by kryshac

When the overlay is opening 'left-ward' (the content flows to the left) the margin is not calculated correctly because the margin is subtracted twice from the width ([line: 1092](https://github.com/angular/components/blob/0762d69b394343555488b5aaada9444dd1a5083a/src/cdk/overlay/position/flexible-connected-position-strategy.ts#L1092)), but [here](https://github.com/angular/components/blob/0762d69b394343555488b5aaada9444dd1a5083a/src/cdk/overlay/position/flexible-connected-position-strategy.ts#L805) it is added only once

2023-12-05 14:48 UTC, PadureanuAndrei commented
@kryshac you are my hero!! Thank you for this great  solution. You are the best!!!

2023-12-05 14:49 UTC, PadureanuAndrei commented
@kryshac do you want a job? please find me on linkedin if you are interested

2023-12-05 14:58 UTC, PadureanuAndrei requested changes

2023-12-05 14:58 UTC, PadureanuAndrei commented on src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
> +      originElement.style.right = `${right}px`;
Use Renderer2 pls

2023-12-05 23:34 UTC, jelbourn commented
I'm not sure if this is the desired behavior? It's been a _long_ time since I wrote this, but I _think_ that we'd want to keep it such that the rightmost edge of the bounding box is the actual viewport edge minus one margin, no?

2023-12-05 23:52 UTC, kryshac commented
because I have a margin in the viewport, the overlay goes to the right, fixed by how much the margin is set
![image](https://github.com/angular/components/assets/19764133/5e435b29-4887-421f-9dae-a544837c96ef)

2023-12-05 23:58 UTC, kryshac commented
and also the same behavior is implemented when calculating the bottom [line 772](https://github.com/angular/components/blob/0762d69b394343555488b5aaada9444dd1a5083a/src/cdk/overlay/position/flexible-connected-position-strategy.ts#L772)

2024-02-11 20:39 UTC, kryshac commented
@jelbourn @mmalerba hello, what is happening with this pull request?

2024-02-24 19:14 UTC, GiorgiZanqaidze commented
..

2024-02-26 13:32 UTC, merged