feat(material/slider): Support for multi word thumb label text #28599
angular/components pull request #29489
Opened 2024-07-26 06:32 UTC by S-Prosper05

**Fix Text Overflow in Value Indicator Container**

Before:

<img width="290" alt="Screenshot 2024-07-26 at 08 26 28" src="https://github.com/user-attachments/assets/ccaf3c12-6fd5-489b-946c-aad50164caf8">

After:

<img width="244" alt="Screenshot 2024-07-26 at 08 27 14" src="https://github.com/user-attachments/assets/456c68dd-89a8-4441-8d74-e2c131ed6190">

2024-08-14 07:09 UTC, Wiggly8193 commented
Hi @crisbeto, May you please review this PR.

2025-02-20 01:59 UTC, mmalerba approved these changes

2025-02-20 15:45 UTC, mmalerba requested changes
I tried running this against Google's internal tests, but there were some failures because this inadvertently removed the callout arrow. You can actually see this in the screenshots you posted:

![image](https://github.com/user-attachments/assets/1d61bd60-1215-4dad-b746-1047f9164369)

2026-03-26 13:50 UTC, crisbeto commented
Closing since there hasn't been any activity in a long time and there are merge conflicts.

2026-03-26 13:50 UTC, closed without merging