Fix stepper icon color in M2
angular/components pull request #29564
Opened 2024-08-09 16:09 UTC by json-derulo

Currently, in M2 theming the step icon theming does not work correctly. The foreground color uses the contrast color of the primary color, but this does not necessarily provide enough contrast to the background. With this changes, the default foreground color is adjusted to ensure sufficient contrast to the background, regardless of the primary color.

Fixes #29518

2025-02-20 00:10 UTC, mmalerba requested changes

2025-02-20 00:10 UTC, mmalerba commented on src/material/core/m2/_palette.scss
> +  stepper-icon: $dark-secondary-text,
I think at this stage we probably don't want to add new entires to this map, but it should be ok to redefine the tokens in terms of these existing properties

2025-02-22 18:04 UTC, json-derulo commented on src/material/core/m2/_palette.scss
> +  stepper-icon: $dark-secondary-text,
@mmalerba For the background color I can revert the changes, but for the foreground colors the problem is that I could not find any value in the existing palettes which produces white for light themes and black for dark themes. How exactly can I define these values, without extending the palettes?

2025-04-17 17:41 UTC, json-derulo commented on src/material/core/m2/_palette.scss
> +  stepper-icon: $dark-secondary-text,
@mmalerba I eventually figured it out, please review again.

2025-04-17 18:18 UTC, andrewseguin commented
If the contrast is not sufficient, you can adjust which values are used when you use `m2-define-palette`. The current implementation seems appropriate to say that it uses the color, and then its defined contrast color

2025-04-17 18:18 UTC, closed without merging

2025-04-17 20:09 UTC, json-derulo commented
@andrewseguin Thanks for checking the PR. However I believe changing the values in the palettes won't properly fix the underlying issue. The problem is that currently the foreground color of the header icon is set to the contrast color of the primary color. This is wrong, because the background of this icon is not the primary color but some other gray color.

So instead of making the color of the header icon depend on the primary contrast color, this value should instead be set to a value which gives better contrast to the gray background. Which is white for light theme and black for dark theme.

Also feel free to play around in the dev app, there the issue is visible in dark mode.