fix(docs): add example for adding icon in meta section using matListI…
angular/components pull request #30068
Opened 2024-11-22 13:49 UTC by im100ra

resolves #26415

2024-11-22 22:35 UTC, AlirezaEbrahimkhani requested changes

2024-11-22 22:35 UTC, AlirezaEbrahimkhani commented on src/material/list/list.md
> +      <mat-icon>folder</mat-icon>
Please add proper indentation to this line for better readability.

2024-11-23 08:52 UTC, AlirezaEbrahimkhani approved these changes

2024-11-27 12:22 UTC, crisbeto approved these changes

2024-11-27 12:23 UTC, merged